import type { RestaurantRequest } from "../../types/restaurantRequest";

export const seederRestaurantRequests: Omit<RestaurantRequest, "id" | "createdAt" | "updatedAt">[] = [
  {
    ownerId: "user1",
    restaurantName: "Khmer Food House",
    description: "Traditional Khmer food featuring authentic recipes from Phnom Penh",
    location: "Phnom Penh",
    status: "pending",
    cuisineType: "Cambodian",
    seatingCapacity: 50,
    phone: "0123456789",
    email: "khmer.food@restaurant.com",
    documents: ["Business License", "Health Certificate", "Food Safety Permit"],
  },
  {
    ownerId: "user2",
    restaurantName: "Sushi Tokyo",
    description: "Premium sushi and Japanese cuisine. Fresh fish imported daily from Tokyo fish market",
    location: "Phnom Penh, Khan Daun Penh",
    status: "pending",
    cuisineType: "Japanese",
    seatingCapacity: 40,
    phone: "0987654321",
    email: "sushi.tokyo@restaurant.com",
    documents: ["Business License", "Health Certificate"],
  },
  {
    ownerId: "user3",
    restaurantName: "Pho Saigon",
    description: "Authentic Vietnamese pho with traditional beef broth recipe. Family-owned since 1995",
    location: "Phnom Penh, Toul Kork",
    status: "pending",
    cuisineType: "Vietnamese",
    seatingCapacity: 60,
    phone: "0118844322",
    email: "pho.saigon@restaurant.com",
    documents: ["Business License", "Health Certificate", "Food Handler Certification"],
  },
  {
    ownerId: "user4",
    restaurantName: "La Bella Italia",
    description: "Authentic Italian cuisine with handmade pasta and wood-fired pizza oven",
    location: "Phnom Penh, BKK1",
    status: "pending",
    cuisineType: "Italian",
    seatingCapacity: 70,
    phone: "0912345678",
    email: "bella.italia@restaurant.com",
    documents: ["Business License", "Health Certificate", "Liquor License"],
  },
  {
    ownerId: "user5",
    restaurantName: "Dragon Palace",
    description: "Chinese cuisine specializing in Szechuan and Cantonese dishes. Hot pot and dim sum",
    location: "Phnom Penh, Russian Blvd",
    status: "pending",
    cuisineType: "Chinese",
    seatingCapacity: 80,
    phone: "0908652390",
    email: "dragon.palace@restaurant.com",
    documents: ["Business License", "Health Certificate", "Fire Safety Certificate"],
  },
  {
    ownerId: "user6",
    restaurantName: "Burger King Premium",
    description: "Premium charbroiled burgers with organic ingredients. Fresh-cut fries daily",
    location: "Phnom Penh, Monivong Blvd",
    status: "approved",
    cuisineType: "American",
    seatingCapacity: 100,
    phone: "012003344",
    email: "burger.premium@restaurant.com",
    documents: ["Franchise License", "Business License", "Health Certificate"],
  },
  {
    ownerId: "user7",
    restaurantName: "Thai Street Kitchen",
    description: "Traditional Thai street food and home-style cooking. Pad Thai, Green Curry, Tom Yum",
    location: "Phnom Penh, Street 63",
    status: "approved",
    cuisineType: "Thai",
    seatingCapacity: 45,
    phone: "0876543210",
    email: "thai.street@restaurant.com",
    documents: ["Business License", "Health Certificate"],
  },
  {
    ownerId: "user8",
    restaurantName: "Romdoul Fine Dining",
    description: "Upscale Khmer cuisine with modern presentation celebrating Cambodia's culinary heritage",
    location: "Phnom Penh, Kampuchea Krom Blvd",
    status: "approved",
    cuisineType: "Cambodian Fine Dining",
    seatingCapacity: 45,
    phone: "088234433",
    email: "romdoul.fine@restaurant.com",
    documents: ["Business License", "Health Certificate", "Liquor License"],
  },
  {
    ownerId: "user9",
    restaurantName: "Fusion Café",
    description: "Modern fusion cuisine blending Asian and Western flavors. Vegetarian options available",
    location: "Phnom Penh, Sisowath Quay",
    status: "rejected",
    cuisineType: "Fusion",
    seatingCapacity: 55,
    phone: "097090988",
    email: "fusion.cafe@restaurant.com",
    documents: ["Business License", "Health Certificate"],
    rejectionReason: "Requires additional health and safety documentation",
  },
  {
    ownerId: "user10",
    restaurantName: "Sakura Ramen",
    description: "Japanese ramen shop with 10 different broth varieties. Tonkotsu, Miso, Shoyu, and more",
    location: "Phnom Penh, Street 240",
    status: "rejected",
    cuisineType: "Japanese",
    seatingCapacity: 35,
    phone: "088112233",
    email: "sakura.ramen@restaurant.com",
    documents: ["Business License", "Health Certificate"],
    rejectionReason: "Location does not meet zoning requirements",
  },
];
